// Day_8/Angular_demos/my-angular-app1/src/app/lucky-number/lucky-number.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-lucky-number',
  template: `
    <div class="luckyNumber">
      <button (click)="generate()">Click to generate Lucky number</button>
      <h1 *ngIf="luckyNumber>0">Your lucky number is {{luckyNumber}}</h1>
    </div>
    
  `,
  styles: [  ]
})
export class LuckyNumberComponent {

   luckyNumber!: number;

   generate(){
     this.luckyNumber=Math.ceil(Math.random()*10);
   }

}

// React_demos/my-app/src/components/LuckyNumber.js
import { useState } from "react";

function LuckyNumber(){
     
    const[luckyNumber,setLuckyNumber]=useState();
    var i=0;

    function generate(){
        if(i==0){
            setLuckyNumber(Math.ceil(Math.random()*10));
            i++;
        }
        else{

        }
        
        // document.getElementById("btn").disabled=true;
        let btn=document.getElementById("btn");
        btn.removeEventListener("onClick",generate);

    }
    return (
        <div>
            {luckyNumber>0 && <h1>Your Lucky number is {luckyNumber}</h1>}
            <button type="Button" id="btn" onClick={generate}>Generate Random number</button>
        </div>
    );
}
export default function LuckyNumber1(){
    return(
        <h1>Hii I am from Lucky number version2</h1>
    );
}
export {LuckyNumber};
